variables:
  IMAGE_NAME: $REGISTRY_USER/maze
  IMAGE_TAG: v1

stages:
  - build
  - test

e2e_test:
  stage: test
  image: node:18
  services:
    - name: docker:20.10.16-dind
  before_script:
    - docker version
    - docker-compose version
  script:
    - docker-compose down
    - docker-compose up -d
    - sleep 15
    - docker-compose exec -T maze npm run test  

build_image:
  stage: build
  image: docker:20.10.16
  services:
    - name: docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"

  before_script:
    - npm install -g npm
    - docker version
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG
