variables:
  IMAGE_NAME: $REGISTRY_USER/maze
  IMAGE_TAG: v1

stages:
  - build
  - test

before_script:
  - npm install npm@10 -g
build_image:
  stage: build
  image: docker:20.10.16
  services:
    - name: docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"

  before_script:
    - apt-get update
    - docker version
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG

e2e_test:
  stage: test
  image: docker:20.10.16
  services:
    - name: docker:20.10.16-dind
  before_script:
    - apt-get update && apt-get install -y docker-compose
    - docker version
    - docker compose version
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD
    - docker pull tdkha1810/maze:v1
  script:
    - docker info
    - docker compose config
    - docker compose up --verbose
    - sleep 15
    - docker compose exec -T tdkha1810/maze:v1 npm run test  
