version: "3.4"
services:
  app:
    image: tieuduykha1810/maze:v1
    ports:
      - "5173:5173"
    restart: unless-stopped
    healthcheck:
      test: wget --quiet --tries=1 --spider http://localhost:5173 || exit 1z
      interval: 30s
      timeout: 10s
      retries: 5