version: "3.4"
services:
  maze:
    image:  registry.gitlab.com/tdkha/maze:latest
    ports:
      - "5173:5173"
    restart: unless-stopped
    healthcheck:
      test: wget --quiet --tries=1 --spider http://localhost:5173 || exit 1z
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
          - web
  #   depends_on: 
  #         - chrome
  # chrome:
  #     image: selenium/standalone-chrome
  #     hostname: localhost
  #     privileged: true
  #     shm_size: 2g
  #     ports:
  #         - "4444:4444"
  #     networks:
  #         - web
  # e2e:
  #     build:
  #       context: .
  #       dockerfile: ./test/Dockerfile
  #     depends_on: 
  #         - maze
  #     networks:
  #       - web
      
networks:
    web: